---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-snapmirror-relationships.html'
summary: 'Retrieve information for SnapMirror relationships'
---

= Retrieve information for SnapMirror relationships

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/snapmirror/relationships`#

*Introduced In:* 9.6

Retrieves information for SnapMirror relationships whose destination endpoints are in the current SVM or the current cluster, depending on the cluster context.

== Related ONTAP commands

* `snapmirror show`
* `snapmirror list-destinations`

== Expensive properties

* `fabriclink.pull_byte_count`
* `fabriclink.push_byte_count`
* `fabriclink.pending_work_task_count`
* `fabriclink.status`
* `source.consistency_group_volumes.name`
* `destination.consistency_group_volumes.name`

== Examples

The following examples show how to retrieve the list of SnapMirror relationships and the list of SnapMirror destinations.

. Retrieving the list of SnapMirror relationships. This API must be run on the cluster containing the destination endpoint.

----
 GET "/api/snapmirror/relationships/"
----

. Retrieving the list of SnapMirror destinations on source. This must be run on the cluster containing the source endpoint.

----
 GET "/api/snapmirror/relationships/?list_destinations_only=true"
----

. Retrieving the relationship UUID of SnapMirror relationships with lag time greater than 2 days. This API must be run on the cluster containing the destination endpoint.

----
 GET "/api/snapmirror/relationships/?fields=uuid&lag_time=>P2DT"
----

. Retrieving the list of SnapMirror relationships with lag time less than 10 hours. This API must be run on the cluster containing the destination endpoint.

----
 GET "/api/snapmirror/relationships/?lag_time=<PT10H"
----

. Retrieving the destination UUID information for object store SnapMirror relationships.

----
 GET "/api/snapmirror/relationships/?fields=destination.uuid"
----

== Learn more

* link:manage_snapmirror_relationships.html[DOC /snapmirror/relationships]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|list_destinations_only
|boolean
|query
|False
a|Set to true to show relationships from the source only.


|destination.cluster.name
|string
|query
|False
a|Filter by destination.cluster.name

* Introduced in: 9.7


|destination.cluster.uuid
|string
|query
|False
a|Filter by destination.cluster.uuid

* Introduced in: 9.7


|destination.svm.uuid
|string
|query
|False
a|Filter by destination.svm.uuid


|destination.svm.name
|string
|query
|False
a|Filter by destination.svm.name


|destination.path
|string
|query
|False
a|Filter by destination.path


|destination.uuid
|string
|query
|False
a|Filter by destination.uuid

* Introduced in: 9.11


|destination.consistency_group_volumes.name
|string
|query
|False
a|Filter by destination.consistency_group_volumes.name

* Introduced in: 9.8


|transfer.total_duration
|string
|query
|False
a|Filter by transfer.total_duration

* Introduced in: 9.9


|transfer.end_time
|string
|query
|False
a|Filter by transfer.end_time

* Introduced in: 9.9


|transfer.bytes_transferred
|integer
|query
|False
a|Filter by transfer.bytes_transferred


|transfer.uuid
|string
|query
|False
a|Filter by transfer.uuid


|transfer.state
|string
|query
|False
a|Filter by transfer.state


|uuid
|string
|query
|False
a|Filter by uuid


|transfer_schedule.uuid
|string
|query
|False
a|Filter by transfer_schedule.uuid

* Introduced in: 9.11


|transfer_schedule.name
|string
|query
|False
a|Filter by transfer_schedule.name

* Introduced in: 9.11


|lag_time
|string
|query
|False
a|Filter by lag_time


|source.cluster.name
|string
|query
|False
a|Filter by source.cluster.name

* Introduced in: 9.7


|source.cluster.uuid
|string
|query
|False
a|Filter by source.cluster.uuid

* Introduced in: 9.7


|source.svm.uuid
|string
|query
|False
a|Filter by source.svm.uuid


|source.svm.name
|string
|query
|False
a|Filter by source.svm.name


|source.path
|string
|query
|False
a|Filter by source.path


|source.uuid
|string
|query
|False
a|Filter by source.uuid

* Introduced in: 9.11


|source.consistency_group_volumes.name
|string
|query
|False
a|Filter by source.consistency_group_volumes.name

* Introduced in: 9.8


|fabriclink.pull_byte_count
|integer
|query
|False
a|Filter by fabriclink.pull_byte_count

* Introduced in: 9.11


|fabriclink.pending_work_task_count
|integer
|query
|False
a|Filter by fabriclink.pending_work_task_count

* Introduced in: 9.11


|fabriclink.topology_uuid
|string
|query
|False
a|Filter by fabriclink.topology_uuid

* Introduced in: 9.11


|fabriclink.push_byte_count
|integer
|query
|False
a|Filter by fabriclink.push_byte_count

* Introduced in: 9.11


|fabriclink.source_bucket
|string
|query
|False
a|Filter by fabriclink.source_bucket

* Introduced in: 9.11


|fabriclink.destination_bucket
|string
|query
|False
a|Filter by fabriclink.destination_bucket

* Introduced in: 9.11


|fabriclink.destination_role
|string
|query
|False
a|Filter by fabriclink.destination_role

* Introduced in: 9.11


|fabriclink.source_role
|string
|query
|False
a|Filter by fabriclink.source_role

* Introduced in: 9.11


|fabriclink.status
|string
|query
|False
a|Filter by fabriclink.status

* Introduced in: 9.11


|restore
|boolean
|query
|False
a|Filter by restore


|last_transfer_type
|string
|query
|False
a|Filter by last_transfer_type

* Introduced in: 9.11


|throttle
|integer
|query
|False
a|Filter by throttle

* Introduced in: 9.11


|unhealthy_reason.parameters
|string
|query
|False
a|Filter by unhealthy_reason.parameters


|unhealthy_reason.code
|integer
|query
|False
a|Filter by unhealthy_reason.code


|unhealthy_reason.message
|string
|query
|False
a|Filter by unhealthy_reason.message


|policy.transfer_schedule.name
|string
|query
|False
a|Filter by policy.transfer_schedule.name

* Introduced in: 9.11


|policy.type
|string
|query
|False
a|Filter by policy.type


|policy.uuid
|string
|query
|False
a|Filter by policy.uuid


|policy.name
|string
|query
|False
a|Filter by policy.name


|identity_preservation
|string
|query
|False
a|Filter by identity_preservation

* Introduced in: 9.11


|group_type
|string
|query
|False
a|Filter by group_type

* Introduced in: 9.11


|exported_snapshot
|string
|query
|False
a|Filter by exported_snapshot


|consistency_group_failover.status.code
|string
|query
|False
a|Filter by consistency_group_failover.status.code

* Introduced in: 9.8


|consistency_group_failover.status.message
|string
|query
|False
a|Filter by consistency_group_failover.status.message

* Introduced in: 9.8


|consistency_group_failover.error.arguments.message
|string
|query
|False
a|Filter by consistency_group_failover.error.arguments.message

* Introduced in: 9.8


|consistency_group_failover.error.arguments.code
|string
|query
|False
a|Filter by consistency_group_failover.error.arguments.code

* Introduced in: 9.8


|consistency_group_failover.error.target
|string
|query
|False
a|Filter by consistency_group_failover.error.target

* Introduced in: 9.8


|consistency_group_failover.error.code
|string
|query
|False
a|Filter by consistency_group_failover.error.code

* Introduced in: 9.8


|consistency_group_failover.error.message
|string
|query
|False
a|Filter by consistency_group_failover.error.message

* Introduced in: 9.8


|healthy
|boolean
|query
|False
a|Filter by healthy


|state
|string
|query
|False
a|Filter by state


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#snapmirror_relationship[snapmirror_relationship]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "consistency_group_failover": {
        "error": {
          "arguments": [
            {
              "code": "string",
              "message": "string"
            }
          ],
          "code": "4",
          "message": "entry doesn't exist",
          "target": "uuid"
        },
        "status": {
          "code": "string",
          "message": "string"
        }
      },
      "destination": {
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "consistency_group_volumes": [
          {
            "name": "volume1"
          }
        ],
        "path": "svm1:volume1",
        "svm": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        },
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "exported_snapshot": "string",
      "fabriclink": {
        "destination_bucket": "string",
        "destination_role": "string",
        "source_bucket": "string",
        "source_role": "string",
        "status": "string",
        "topology_uuid": "string"
      },
      "group_type": "consistency_group",
      "identity_preservation": "string",
      "lag_time": "PT8H35M42S",
      "last_transfer_type": "initialize",
      "policy": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "Asynchronous",
        "transfer_schedule": {
          "name": "hourly"
        },
        "type": "string",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "restore_to_snapshot": "string",
      "source": {
        "cluster": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "cluster1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "consistency_group_volumes": [
          {
            "name": "volume1"
          }
        ],
        "path": "svm1:volume1",
        "svm": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        },
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "state": "snapmirrored",
      "throttle": 0,
      "transfer": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "end_time": "2020-12-02T18:36:19-08:00",
        "state": "string",
        "total_duration": "PT28M41S",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "transfer_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "unhealthy_reason": [
        {
          "code": "6621444",
          "message": "Failed to complete update operation on one or more item relationships.",
          "parameters": []
        },
        {
          "code": "6621445",
          "message": "Group Update failed",
          "parameters": []
        }
      ],
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303825
| Could not retrieve information for the SnapMirror policy type

| 13303817
| Unknown value for the Snapmirror State
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Status code


|message
|string
a|SnapMirror Consistency Group failover status.


|===


[#snapmirror_consistency_group_failover]
[.api-collapsible-fifth-title]
snapmirror_consistency_group_failover

SnapMirror Consistency Group failover information. The SnapMirror Consistency Group failover can be a planned or an unplanned operation. Only active SnapMirror Consistency Group failover operation progress can be monitored using this object. In case of an error during the failover operation, the property "consistency_group_failover.error" holds the reason for the error. ONTAP automatically retries any failed SnapMirror Consistency Group failover operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|status
|link:#status[status]
a|

|===


[#storage_service]
[.api-collapsible-fifth-title]
storage_service

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|This property indicates whether to create the destination endpoint using storage service.


|enforce_performance
|boolean
a|Optional property to enforce storage service performance on the destination endpoint. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints.


|name
|string
a|Optional property to specify the storage service name for the destination endpoint. This property is considered when the property "create_destination.storage_service.enabled" is set to "true". When the property "create_destination.storage_service.enabled" is set to "true" and the "create_destination.storage_service.name" for the endpoint is not specified, then ONTAP selects the highest storage service available on the cluster to provision the destination endpoint. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints.

* enum: ["extreme", "performance", "value"]
* Introduced in: 9.6


|===


[#tiering]
[.api-collapsible-fifth-title]
tiering

[cols=3*,options=header]
|===
|Name
|Type
|Description

|policy
|string
a|Optional property to specify the destination endpoint's tiering policy when "create_destination.tiering.supported" is set to "true". This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. This property determines whether the user data blocks of the destination endpoint in a FabricPool will be tiered to the cloud store when they become cold. FabricPool combines flash (performance tier) with a cloud store into a single aggregate. Temperature of the destination endpoint volume blocks increases if they are accessed frequently and decreases when they are not.
all &dash; This policy allows tiering of both destination endpoint Snapshot copies and the user transfered data blocks to the cloud store as soon as possible by ignoring the temperature on the volume blocks. This tiering policy is not applicable for Consistency Group destination endpoints or for synchronous relationships.
auto &dash; This policy allows tiering of both destination endpoint Snapshot copies and the active file system user data to the cloud store
none &dash; Destination endpoint volume blocks will not be tiered to the cloud store.
snapshot_only &dash; This policy allows tiering of only the destination endpoint volume Snapshot copies not associated with the active file system. The default tiering policy is "snapshot_only" for a FlexVol volume and "none" for a FlexGroup volume.


|supported
|boolean
a|Optional property to enable provisioning of the destination endpoint volumes on FabricPool aggregates. This property is applicable to FlexVol volume, FlexGroup volume, and Consistency Group endpoints. Only FabricPool aggregates are used if this property is set to "true" and only non FabricPool aggregates are used if this property is set to "false". Tiering support for a FlexGroup volume can be changed by moving all of the constituents to the required aggregates. Note that in order to tier data, not only do the destination endpoint volumes need to support tiering by using FabricPools, the "create_destination.tiering.policy" must not be "none". A destination endpoint that uses FabricPools but has a tiering "policy" of "none" supports tiering but will not tier any data.


|===


[#snapmirror_destination_creation]
[.api-collapsible-fifth-title]
snapmirror_destination_creation

Use this object to provision the destination endpoint when establishing a SnapMirror relationship for a FlexVol volume, FlexGroup volume, SVM, Consistency Group or ONTAP S3 Bucket. Given a source endpoint, the destination endpoint is provisioned in the SVM specified in the "destination.path" property. While protecting an SVM, the SVM destination endpoint can only be provisioned on the local cluster. To provision the SVM destination endpoint use the optional "source.cluster.name" property to specify the remote cluster name or use the optional "source.cluster.uuid" property to specify the remote cluster UUID. When "create_destination.enabled" option is specified while making a POST for a SnapMirror relationship, the relationship can be automatically initialized by setting the "state" either to "snapmirrored" when the policy is of type "async" or to "in_sync" when the policy is of type "sync". The "destination.path" property must specify the destination endpoint path. For example, for FlexVol volume and FlexGroup volume, the "destination.path" can be specified as +++<destination-svm-name:dp-volume-name>+++, for SVM data protection, the "destination.path" must be specified as <destination-svm-name:>, and for Consistency Group, the "destination.path" must be specified as <destination-svm-name:> along with the "destination.consistency_group_volumes" property to indicate the list of destination volumes of type "DP" in the Consistency Group. For a FlexVol volume, a FlexGroup volume, Consistency Group or a Bucket destination endpoint, the properties in this object can be specified either from the source or the destination cluster. For an SVM destination endpoint, the properties in this object can be specified from the destination cluster only. This object is not supported for non ONTAP endpoints. While protecting a S3 Bucket, the optional "size" property can be used to create ONTAP S3 Bucket destination endpoint of the specified size.</destination-svm-name:></destination-svm-name:>+++</destination-svm-name:dp-volume-name>+++


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Optional property to create the destination endpoint when establishing a SnapMirror relationship. It is assumed to be "false" if no other property is set and assumed to be "true" if any other property is set.


|size
|integer
a|Optional property to specify the size of destination endpoint in bytes. This property is applicable only to ONTAP S3 Bucket endpoints. The minimum size for S3 bucket is 80MB and maximum size is 64TB. If not specified, system will create destination with default size of 800GB.

* Introduced in: 9.10


|storage_service
|link:#storage_service[storage_service]
a|

|tiering
|link:#tiering[tiering]
a|

|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#consistency_group_volumes]
[.api-collapsible-fifth-title]
consistency_group_volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#snapmirror_endpoint]
[.api-collapsible-fifth-title]
snapmirror_endpoint

Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|consistency_group_volumes
|array[link:#consistency_group_volumes[consistency_group_volumes]]
a|Mandatory property for a Consistency Group endpoint. Specifies the list of FlexVol volumes for a Consistency Group.


|path
|string
a|ONTAP FlexVol/FlexGroup - svm1:volume1
ONTAP SVM               - svm1:
ONTAP Consistency Group - svm1:/cg/cg_name
ONTAP S3                - svm1:/bucket/bucket1
NON-ONTAP               - objstore1:/objstore

* example: svm1:volume1
* Introduced in: 9.6


|svm
|link:#svm[svm]
a|

|uuid
|string
a|UUID of the endpoint. Applicable for object store SnapMirror relationships only.


|===


[#fabriclink]
[.api-collapsible-fifth-title]
fabriclink

SnapMirror FabricLink relationship


[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination_bucket
|string
a|Specifies the name of the destination bucket of the FabricLink SnapMirror relationship. This parameter is supported for FabricLink SnapMirror relationships with ONTAP or external object store vendor endpoints. This parameter is only available on ONTAP 9.10.1 or later.

* Introduced in: 9.11
* readOnly: 1


|destination_role
|string
a|This field represents the destination bucket's role within FabricLink. Possible values for this field are "active_mirror" and "backup". In a bi-directional ONTAP to ONTAP mirroring relationship, both FabricLink SnapMirror records will contain "active_mirror" in both the source-role and destination-role fields. This field conveys that both mirrors are capable of performing an active role at any time. In an ONTAP to Non-ONTAP FabricLink replication relationship, the source-role is "active_mirror" and the destination-role is "backup". This parameter is supported for FabricLink SnapMirror relationships with ONTAP or external object store vendor endpoints. This parameter is only available in ONTAP 9.10.1 or later.

* enum: ["active_mirror", "backup"]
* Introduced in: 9.11
* readOnly: 1


|pending_work_task_count
|integer
a|Conveys how many discrete tasks the bucket in this unidirectional FabricLink SnapMirror relationship knows it will eventually have to perform to fully update the destination to reflect the source's state. Each work item might represent the need to push a newly created object from the source to the destination mirror, or perhaps to advise the destination mirror that an existing object has been modified or deleted. If the link is configured with an RPO of one hour and the user creates an object on the source bucket, that bucket will immediately show that it now has a pending work item to send that new object to the destination; FabricLink intentionally will not act on that work item until the hour has elapsed. This parameter is only available in ONTAP 9.10.1 or later.

* Introduced in: 9.11
* readOnly: 1


|pull_byte_count
|integer
a|Represents the approximate number of bytes of data that the destination bucket anticipates reading from the source bucket for the FabricLink SnapMirror relationship. This parameter is only available in ONTAP 9.10.1 or later.

* Introduced in: 9.11
* readOnly: 1


|push_byte_count
|integer
a|Represents the approximate number of bytes of data that must be pushed from the source bucket to the destination bucket for the FabricLink SnapMirror relationship. This parameter is only available in ONTAP 9.10.1 or later.

* Introduced in: 9.11
* readOnly: 1


|source_bucket
|string
a|Specifies the name of the source bucket of the FabricLink SnapMirror relationship. This parameter is supported only for FabricLink SnapMirror relationships with ONTAP endpoints. This parameter is only available in ONTAP 9.10.1 or later.

* Introduced in: 9.11
* readOnly: 1


|source_role
|string
a|This field represents the source bucket's role within FabricLink. One possible value for this field is "active_mirror". In a bi-directional ONTAP to ONTAP mirroring relationship, both FabricLink SnapMirror records will contain "active_mirror" in both the source-role and destination-role fields. This field conveys that both mirrors are capable of performing an active role at any time. In an ONTAP to Non-ONTAP FabricLink replication relationship, the source-role is "active_mirror" and the destination-role is "backup". This parameter is supported only for FabricLink SnapMirror relationships with an ONTAP endpoint. This parameter is only available in ONTAP 9.10.1 or later.

* enum: ["active_mirror"]
* Introduced in: 9.11
* readOnly: 1


|status
|string
a|Specifies the status of the FabricLink SnapMirror relationship. This parameter is only available in ONTAP 9.10.1 or later.

* Introduced in: 9.11
* readOnly: 1


|topology_uuid
|string
a|Topology UUID is used to refer to a unique data set. All the links that connect the same data set share the same topology UUID. Thus, in a fan-out topology, all links fanning from the same source bucket will carry the same topology-uuid value. Similarly, in a cascading mirror arrangement, all links in the cascade will carry the same topology-uuid value. This parameter is only available in ONTAP 9.10.1 or later.

* format: uuid
* Introduced in: 9.11
* readOnly: 1


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

The schedule used to update the asynchronous relationship. This is only applicable when provisioning a destination endpoint on a remote cluster with an effective cluster version of 9.6 or earlier. Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#policy]
[.api-collapsible-fifth-title]
policy

Basic policy information of the relationship.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|The schedule used to update the asynchronous relationship. This is only applicable when provisioning a destination endpoint on a remote cluster with an effective cluster version of 9.6 or earlier. Only cron schedules are supported for SnapMirror.


|type
|string
a|

|uuid
|string
a|

|===


[#transfer]
[.api-collapsible-fifth-title]
transfer

Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|bytes_transferred
|integer
a|Bytes transferred.


|end_time
|string
a|End time of the last transfer.


|state
|string
a|

|total_duration
|string
a|Transfer elapsed time.


|uuid
|string
a|Transfer UUID. This property is applicable only for active transfers.


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_error]
[.api-collapsible-fifth-title]
snapmirror_error

SnapMirror error


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Error code


|message
|string
a|Error message


|parameters
|array[string]
a|Parameters for the error message


|===


[#snapmirror_relationship]
[.api-collapsible-fifth-title]
snapmirror_relationship

SnapMirror relationship information. The SnapMirror relatiosnhip can be either "async" or "sync" based on the type of SnapMirror policy associated with the relationship. The source and destination endpoints of a SnapMirror relationship must be of the same type, for example, if the source endpoint is a FlexVol volume then the destination endpoint must be a FlexVol volume.
The SnapMirror policy type "async" can be used when the SnapMirror relationship has FlexVol volume or FlexGroup volume or SVM as the endpoint. The SnapMirror policy type "sync" can be used when the SnapMirror relationship has FlexVol volume as the endpoint. The SnapMirror policy type "sync" with "sync_type" as "automated_failover" can be used when the SnapMirror relationship has Consistency Group as the endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|consistency_group_failover
|link:#snapmirror_consistency_group_failover[snapmirror_consistency_group_failover]
a|SnapMirror Consistency Group failover information. The SnapMirror Consistency Group failover can be a planned or an unplanned operation. Only active SnapMirror Consistency Group failover operation progress can be monitored using this object. In case of an error during the failover operation, the property "consistency_group_failover.error" holds the reason for the error. ONTAP automatically retries any failed SnapMirror Consistency Group failover operation.

* Introduced in: 9.8
* readOnly: 1


|destination
|link:#snapmirror_endpoint[snapmirror_endpoint]
a|Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.

* Introduced in: 9.6


|exported_snapshot
|string
a|Snapshot copy exported to clients on destination.


|fabriclink
|link:#fabriclink[fabriclink]
a|SnapMirror FabricLink relationship


|group_type
|string
a|Specifies the group type of the top level SnapMirror relationship. The volume relationships are shown as _none_, the SVMDR relationships are shown as _svm_dr_, the Consistency Group relationships are shown as _consistency_group_, and the FlexGroup volume relationships are shown as _flexgroup_.


|healthy
|boolean
a|Is the relationship healthy?


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type. This "identity_preservation" overrides the "identity_preservation" set on the SnapMirror relationship's policy.


|lag_time
|string
a|Time since the exported Snapshot copy was created.


|last_transfer_type
|string
a|Specifies the operation type of the last transfer that occured on the relationship. The _initialize_ transfer occurs when the relationship state changes from uninitialized to snapmirrored or in_sync. The _update_ transfer occurs when the snapshots are transferred from the source endpoint to the destination endpoint as part of scheduled or manual update. The _resync_ transfer occurs when the relationship state changes from broken_off to snapmirrored or in_sync. The _restore_ transfer occurs when the snapshot is restored from a destination endpoint to another endpoint.


|policy
|link:#policy[policy]
a|Basic policy information of the relationship.


|preserve
|boolean
a|Set to true on resync to preserve Snapshot copies on the destination that are newer than the latest common Snapshot copy. This property is applicable only for relationships with FlexVol volume or FlexGroup volume endpoints and when the PATCH state is being changed to "snapmirrored".


|quick_resync
|boolean
a|Set to true to reduce resync time by not preserving storage efficiency. This property is applicable only for relationships with FlexVol volume endpoints and SVMDR relationships when the PATCH state is being changed to "snapmirrored".


|recover_after_break
|boolean
a|Set to true to recover from a failed SnapMirror break operation on a FlexGroup volume relationship. This restores all destination FlexGroup constituent volumes to the latest Snapshot copy, and any writes to the read-write constituents are lost. This property is applicable only for SnapMirror relationships with FlexGroup volume endpoints and when the PATCH state is being changed to "broken_off".


|restore
|boolean
a|Set to true to create a relationship for restore. To trigger restore-transfer, use transfers POST on the restore relationship. SnapMirror relationships with the policy type "async" can be restored. SnapMirror relationships with the policy type "sync" cannot be restored.


|restore_to_snapshot
|string
a|Specifies the Snapshot copy to restore to on the destination during the break operation. This property is applicable only for SnapMirror relationships with FlexVol volume endpoints and when the PATCH state is being changed to "broken_off".


|source
|link:#snapmirror_endpoint[snapmirror_endpoint]
a|Endpoint of a SnapMirror relationship. For a GET request, the property "cluster" is populated when the endpoint is on a remote cluster. A POST request to create the destination SVM endpoint or to establish an SVM DR relationship must have the property "cluster" populated with the remote cluster details. A POST request to create the destination FlexVol volume, FlexGroup volume, Consistency Group, ONTAP S3 bucket and NON-ONTAP object-store endpoints can optionally specify the "cluster" property when the source SVM and the destination SVM are peered. A POST request to establish a SnapMirror relationship between the source endpoint and destination endpoint and when the source SVM and the destination SVM are not peered, must specify the "cluster" property for the remote endpoint.

* Introduced in: 9.6


|state
|string
a|State of the relationship.
To initialize the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
To break the relationship, PATCH the state to "broken_off" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "broken_off".
To resync the relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" can be in "broken_off" state due to a failed attempt of SnapMirror failover.
To pause the relationship, suspending further transfers, PATCH the state to "paused" for relationships with a policy of type "async" or "sync". SnapMirror relationships with the policy type as "sync" and "sync_type" as "automated_failover" cannot be "paused".
To resume transfers for a paused relationship, PATCH the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".
The entries "in_sync", "out_of_sync", and "synchronizing" are only applicable to relationships with a policy of type "sync". A PATCH call on the state change only triggers the transition to the specified state. You must poll on the "state", "healthy" and "unhealthy_reason" properties using a GET request to determine if the transition is successful. To automatically initialize the relationship when specifying "create_destination" property, set the state to "snapmirrored" for relationships with a policy of type "async" or to state "in_sync" for relationships with a policy of type "sync".


|throttle
|integer
a|Throttle, in KBs per second. This "throttle" overrides the "throttle" set on the SnapMirror relationship's policy. If neither of these are set, defaults to 0, which is interpreted as unlimited.


|transfer
|link:#transfer[transfer]
a|Basic information on the current transfer or the last transfer if there is no active transfer at the time of the request.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|Schedule used to update asynchronous relationships. This "transfer_schedule" overrides the "transfer_schedule" set on the SnapMirror relationship's policy. To remove the "transfer_schedule", set its value to null (no-quotes). Only cron schedules are supported for SnapMirror.


|unhealthy_reason
|array[link:#snapmirror_error[snapmirror_error]]
a|Reason the relationship is not healthy. It is a concatenation of up to four levels of error messages.


|uuid
|string
a|

|===


//end collapsible .Definitions block
====
