---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-snapmirror-policies.html'
summary: 'Retrieve SnapMirror async and sync policy types'
---

= Retrieve SnapMirror async and sync policy types

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/snapmirror/policies`#

*Introduced In:* 9.6

Retrieves SnapMirror policies of type "async" and "sync".

== Related ONTAP commands

* `snapmirror policy show`

== Example

The following example shows how to retrieve a collection of SnapMirror policies.

----
GET "/api/snapmirror/policies"
----

== Learn more

* link:manage_snapmirror_policies.html[DOC /snapmirror/policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|name
|string
|query
|False
a|Filter by name


|comment
|string
|query
|False
a|Filter by comment


|sync_type
|string
|query
|False
a|Filter by sync_type


|throttle
|integer
|query
|False
a|Filter by throttle


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|scope
|string
|query
|False
a|Filter by scope


|network_compression_enabled
|boolean
|query
|False
a|Filter by network_compression_enabled


|archive.after_days
|integer
|query
|False
a|Filter by archive.after_days

* Introduced in: 9.11


|archive.enabled
|boolean
|query
|False
a|Filter by archive.enabled

* Introduced in: 9.11


|identity_preservation
|string
|query
|False
a|Filter by identity_preservation


|uuid
|string
|query
|False
a|Filter by uuid


|create_snapshot_on_source
|boolean
|query
|False
a|Filter by create_snapshot_on_source

* Introduced in: 9.11


|type
|string
|query
|False
a|Filter by type


|rpo
|integer
|query
|False
a|Filter by rpo

* Introduced in: 9.10


|copy_all_source_snapshots
|boolean
|query
|False
a|Filter by copy_all_source_snapshots

* Introduced in: 9.10


|retention.count
|integer
|query
|False
a|Filter by retention.count


|retention.creation_schedule.uuid
|string
|query
|False
a|Filter by retention.creation_schedule.uuid


|retention.creation_schedule.name
|string
|query
|False
a|Filter by retention.creation_schedule.name


|retention.prefix
|string
|query
|False
a|Filter by retention.prefix


|retention.period
|string
|query
|False
a|Filter by retention.period

* Introduced in: 9.11


|retention.label
|string
|query
|False
a|Filter by retention.label


|snapshot_lock_mode
|string
|query
|False
a|Filter by snapshot_lock_mode

* Introduced in: 9.11


|transfer_schedule.uuid
|string
|query
|False
a|Filter by transfer_schedule.uuid


|transfer_schedule.name
|string
|query
|False
a|Filter by transfer_schedule.name


|copy_latest_source_snapshot
|boolean
|query
|False
a|Filter by copy_latest_source_snapshot

* Introduced in: 9.11


|sync_common_snapshot_schedule.uuid
|string
|query
|False
a|Filter by sync_common_snapshot_schedule.uuid


|sync_common_snapshot_schedule.name
|string
|query
|False
a|Filter by sync_common_snapshot_schedule.name


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#snapmirror_policy[snapmirror_policy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "comment": "string",
      "copy_all_source_snapshots": 1,
      "copy_latest_source_snapshot": 1,
      "create_snapshot_on_source": "",
      "identity_preservation": "string",
      "name": "Asynchronous",
      "retention": [
        {
          "count": 7,
          "creation_schedule": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "weekly",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "label": "hourly",
          "period": "P30D",
          "prefix": "string"
        }
      ],
      "rpo": 0,
      "scope": "string",
      "snapshot_lock_mode": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "sync_common_snapshot_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "sync_type": "string",
      "throttle": 0,
      "transfer_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "type": "string",
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303842
| SnapMirror policy is not supported.
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#archive]
[.api-collapsible-fifth-title]
archive

Archive information for the objects in an object store SnapMirror relationship. This property is applicable only for "async" policies with "create_snapshot_on_source" set to "false".


[cols=3*,options=header]
|===
|Name
|Type
|Description

|after_days
|integer
a|Number of days after which the objects are archived. This is only applicable when "archive.enabled" is "true". If this property is not set when "archive.enabled" is "true", the default value is "0" and therefore archiving will be triggered instantly. The value range is 0..999. If the value is set to "0", the latest snapshot copy will be archived. The value of after_days cannot be changed from "0" if any FlexVol SnapMirror relationship is associated with the policy.


|enabled
|boolean
a|When set to "true", the objects are archived. When set to "false", the objects are not archived.


|===


[#creation_schedule]
[.api-collapsible-fifth-title]
creation_schedule

Schedule used to create Snapshot copies on the destination for long term retention. Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy_rule]
[.api-collapsible-fifth-title]
snapmirror_policy_rule

SnapMirror policy rule for retention.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of Snapshot copies to be kept for retention.


|creation_schedule
|link:#creation_schedule[creation_schedule]
a|Schedule used to create Snapshot copies on the destination for long term retention. Only cron schedules are supported for SnapMirror.


|label
|string
a|Snapshot copy label


|period
|string
a|Specifies the duration for which the Snapshot copies in the object store are locked. This property is valid only when the property 'snapshot_lock_mode' in the policy is set to enterprise or compliance. The retention period value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, or days. A period specified for years, months, or days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", or "P+++<num>+++D" respectively. For example, "P10Y" represents a duration of 10 years. The period string must contain only a single time element, that is, either years, months, or days. A duration which combines different periods is not supported, for example "P1Y10M" is not supported. Years, if specified, must be less than or equal to 100. Months, if specified, must be less than or equal to 1200. Days, if specified, must be between and including 30 and 36500.+++</num>++++++</num>++++++</num>+++


|prefix
|string
a|Specifies the prefix for the Snapshot copy name to be created as per the schedule. If no value is specified, then the label is used as the prefix.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#sync_common_snapshot_schedule]
[.api-collapsible-fifth-title]
sync_common_snapshot_schedule

Schedule used to create common Snapshot copies for synchronous relationships.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

The schedule used to update asynchronous relationships. Only cron schedules are supported for SnapMirror.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy]
[.api-collapsible-fifth-title]
snapmirror_policy

SnapMirror policy information. SnapMirror policy can either be of type "async", "sync" or "continuous".
The policy type "async" can be associated with a SnapMirror relationship that has either the FlexVol volume or FlexGroup volume or SVM as the endpoint.
The policy type "sync" along with "sync_type" as "sync" or "strict_sync" can be associated with a SnapMirror relationship that has FlexVol volume as the endpoint. The policy type "sync" can have a "sync_type" of either "sync", "strict_sync" or "automated_failover". If the "sync_type" is "sync" then a write success is returned to the client after writing the data to the source endpoint and before writing the data to the destination endpoint. If the "sync_type" is "strict_sync" then a write success is returned to the client after writing the data to the both source and destination endpoints.
If the "sync_type" is "automated_failover" then the policy can be associated with a SnapMirror relationship that has Consistency Group as the endpoint. Use the "sync" policy with "sync_type" as "automated_failover" to establish SnapMirror relationships for business continuity usecases. SnapMirror relationships with policy type as "sync" and "sync_type" as "automated_failover" can be monitored by the Mediator, if configured. In case the source Consistency Group endpoint is not reachable, the Mediator may trigger a failover to the destination Consistency Group endpoint. A policy of type "continuous" can be associated with SnapMirror relationships that have either ONTAP S3 buckets or NON-ONTAP object stores as endpoints. This type of policy is used for FabricLink owned targets.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|archive
|link:#archive[archive]
a|Archive information for the objects in an object store SnapMirror relationship. This property is applicable only for "async" policies with "create_snapshot_on_source" set to "false".


|comment
|string
a|Comment associated with the policy.


|copy_all_source_snapshots
|boolean
a|Specifies that all the source Snapshot copies (including the one created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|copy_latest_source_snapshot
|boolean
a|Specifies that the latest source Snapshot copy (created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|create_snapshot_on_source
|boolean
a|Specifies whether a new Snapshot copy should be created on the source at the beginning of an update or resync operation. This is applicable only to async policies. Property can only be set to 'false'.


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type.


|name
|string
a|Name of the policy.


|network_compression_enabled
|boolean
a|Specifies whether network compression is enabled for transfers. This is applicable only to the policies of type "async".


|retention
|array[link:#snapmirror_policy_rule[snapmirror_policy_rule]]
a|Rules for Snapshot copy retention.


|rpo
|integer
a|Specifies the duration of time for which a change to be propogated to a mirror should be delayed, in seconds. This is an intentional propagation delay between mirrors and is configurable down to zero, which means an immediate propogation. This is supported for policies of type 'continuous'.


|scope
|string
a|Set to "svm" for policies owned by an SVM, otherwise set to "cluster".


|snapshot_lock_mode
|string
a|Specifies the lock mode of the Snapshot copies stored in the object store. This property is applicable only to policies of type "async" with "create_snapshot_on_source" set to "false". When set to enterprise or compliance, the policy can be associated only with SnapMirror relationships where the source endpoint is a FlexVol volume and the destination endpoint is an object store. When set to compliance, no users can delete a Snapshot copy until the retention period has expired. When set to enterprise, users that have special permissions can delete a Snapshot copy before the retention period has expired.


|svm
|link:#svm[svm]
a|

|sync_common_snapshot_schedule
|link:#sync_common_snapshot_schedule[sync_common_snapshot_schedule]
a|Schedule used to create common Snapshot copies for synchronous relationships.


|sync_type
|string
a|

|throttle
|integer
a|Throttle in KB/s. Default to unlimited.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|The schedule used to update asynchronous relationships. Only cron schedules are supported for SnapMirror.


|type
|string
a|

|uuid
|string
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
