---
sidebar: sidebar
api: true
explorer: false
permalink: 'manage_ems_configuration.html'
summary: 'Manage EMS configuration'
---

= Manage EMS configuration



== Overview

The Event Management System (EMS) collects and processes events, and sends notification of the events through various reporting mechanisms. The following endpoints defined under '/support/ems', allow you to query a list of observed events, and configure which events you handle and how you are notified:

* /support/ems
* /support/ems/events
* /support/ems/messages
* /support/ems/filters
* /support/ems/filters/\{name}/rules
* /support/ems/filters/\{name}/rules/\{index}
* /support/ems/destinations
* /support/ems/destinations/\{name}

== Examples

=== Configuring an email destination

The following example configures EMS to send a support email when a WAFL event is observed with an error severity.

==== Configure the system-wide email parameters

[,json]
----

# The API:
PATCH /support/ems

# The call:
curl -X PATCH "https://<mgmt-ip>/api/support/ems" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "@test_ems_config_patch.txt"
test_ems_config_patch.txt(body):
{
"mail_from": "administrator@mycompany.com",
"mail_server": "smtp@mycompany.com"
}

# The response:
200 OK
----

=== Configuring a filter with an enclosed rule

[,json]
----

# The API:
POST /support/ems/filters

# The call:
curl -X POST "https://<mgmt-ip>/api/support/ems/filters" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "@test_ems_filters_post.txt"
test_ems_filters_post.txt(body):
{
"name": "critical-wafl",
"rules": [
  {
    "index": 1,
    "type": "include",
    "message_criteria": {
      "name_pattern": "wafl.*",
      "severities": "emergency,error,alert"
    }
  }
]
}

# The response:
201 Created
----

=== Setting up an email destination

[,json]
----

# The API:
POST /support/ems/destinations

# The call:
curl -X POST "https://<mgmt-ip>/api/support/ems/destinations" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "@test_ems_dest_post.txt"
test_ems_dest_post.txt(body):
{
"name": "Technician_Email",
"type": "email",
"destination": "technician@mycompany.com",
"filters": [
  { "name" : "critical-wafl" }
]
}

# The response:
201 Created
----


