---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-san-igroups-initiators.html'
summary: 'Add initiators to an initiator group'
---

= Add initiators to an initiator group

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/san/igroups/{igroup.uuid}/initiators`#

*Introduced In:* 9.6

Adds one or more initiators to an initiator group.
This API does not support adding initiators to an initiator group that
already contains nested initiator groups.

== Required properties

* `name` or `records.name` - Initiator name(s) to add to the initiator group.

== Related ONTAP commands

* `lun igroup add`

== Learn more

* link:manage_san_igroups.html[DOC /protocols/san/igroups]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|igroup.uuid
|string
|path
|True
a|The unique identifier of the initiator group.


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|connectivity_tracking
|link:#connectivity_tracking[connectivity_tracking]
a|Overview of the initiator's connections to ONTAP.

* readOnly: 1
* Introduced in: 9.11


|igroup
|link:#igroup[igroup]
a|The initiator group in which the initiator is found.

Note that this does not mean that the initiator cannot also be found in other initiator groups.


|name
|string
a|The FC WWPN, iSCSI IQN, or iSCSI EUI that identifies the host initiator. Valid in POST only and not allowed when the `records` property is used.

An FC WWPN consists of 16 hexadecimal digits grouped as 8 pairs separated by colons. The format for an iSCSI IQN is _iqn.yyyy-mm.reverse_domain_name:any_. The iSCSI EUI format consists of the _eui._ prefix followed by 16 hexadecimal characters.


|records
|array[link:#records[records]]
a|An array of initiators specified to add multiple initiators to an initiator group in a single API call. Not allowed when the `name` property is used.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "comment": "string",
  "connectivity_tracking": {
    "alerts": [
      {
        "summary": {
          "arguments": [
            {
              "code": "string",
              "message": "string"
            }
          ],
          "code": "4",
          "message": "entry doesn't exist",
          "target": "uuid"
        }
      }
    ],
    "connection_state": "string",
    "connections": [
      {
        "logins": [
          {
            "interface": {
              "fc": {
                "name": "fc_lif1",
                "uuid": "3a09ab42-4da1-32cf-9d35-3385a6101a0b",
                "wwpn": "20:00:00:50:56:b4:13:a8"
              },
              "ip": {
                "name": "lif1",
                "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
              }
            },
            "last_seen_time": "2021-03-14T05:19:00Z"
          }
        ],
        "node": {
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      }
    ]
  },
  "igroup": {
    "name": "igroup1",
    "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
  },
  "name": "iqn.1998-01.com.corp.iscsi:name1",
  "records": [
    {
      "comment": "string",
      "name": "iqn.1998-01.com.corp.iscsi:name1"
    }
  ]
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|The number of records in the response.


|records
|array[link:#igroup_initiator[igroup_initiator]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "num_records": 1,
  "records": [
    {
      "comment": "string",
      "connectivity_tracking": {
        "alerts": [
          {
            "summary": {
              "arguments": [
                {
                  "code": "string",
                  "message": "string"
                }
              ],
              "code": "4",
              "message": "entry doesn't exist",
              "target": "uuid"
            }
          }
        ],
        "connection_state": "string",
        "connections": [
          {
            "logins": [
              {
                "interface": {
                  "fc": {
                    "name": "fc_lif1",
                    "uuid": "3a09ab42-4da1-32cf-9d35-3385a6101a0b",
                    "wwpn": "20:00:00:50:56:b4:13:a8"
                  },
                  "ip": {
                    "name": "lif1",
                    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
                  }
                },
                "last_seen_time": "2021-03-14T05:19:00Z"
              }
            ],
            "node": {
              "name": "node1",
              "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
            }
          }
        ]
      },
      "igroup": {
        "name": "igroup1",
        "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
      },
      "name": "iqn.1998-01.com.corp.iscsi:name1",
      "records": [
        {
          "comment": "string",
          "name": "iqn.1998-01.com.corp.iscsi:name1"
        }
      ]
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1254193
| Adding an initiator would cause the initiator to be mapped to the same LUN more than once.

| 1254324
| Adding an initiator would cause the initiator to have the same logical unit identifier for multiple LUN maps.

| 5373969
| A supplied initiator name looks like an iSCSI IQN initiator, but the portions after the prefix are missing.

| 5373971
| A supplied initiator name looks like an iSCSI IQN initiator, but the date portion is invalid.

| 5373972
| A supplied initiator name looks like an iSCSI IQN initiator, but the naming authority portion is invalid.

| 5373977
| A supplied initiator name looks like an iSCSI EUI initiator, but the length is invalid.

| 5373978
| A supplied initiator name looks like an iSCSI EUI initiator, but the format is invalid.

| 5373992
| A supplied initiator name was too long to be valid.

| 5373993
| A supplied initiator name did not match any valid format.

| 5374033
| Initiators must be supplied.

| 5374035
| A supplied initiator is already in the initiator group.

| 5374038
| An invalid Fibre Channel WWPN was supplied.

| 5374039
| An invalid iSCSI initiator name was supplied.

| 5374734
| An initiator is already in another initiator group with a conflicting operating system type.

| 5374852
| The initiator group specified in the URI does not exist.

| 5374917
| Multiple matching initiators have been supplied with conflicting comments.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#summary]
[.api-collapsible-fifth-title]
summary

A user friendly message describing the connection state.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


[#alerts]
[.api-collapsible-fifth-title]
alerts

[cols=3*,options=header]
|===
|Name
|Type
|Description

|summary
|link:#summary[summary]
a|A user friendly message describing the connection state.


|===


[#fc]
[.api-collapsible-fifth-title]
fc

An FC interface.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the FC interface.


|uuid
|string
a|The unique identifier of the FC interface.


|wwpn
|string
a|The WWPN of the FC interface.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information

[#ip]
[.api-collapsible-fifth-title]
ip

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface. If only the name is provided, the SVM scope
must be provided by the object this object is embedded in.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#interface]
[.api-collapsible-fifth-title]
interface

[cols=3*,options=header]
|===
|Name
|Type
|Description

|fc
|link:#fc[fc]
a|An FC interface.


|ip
|link:#ip[ip]
a|

|===


[#logins]
[.api-collapsible-fifth-title]
logins

[cols=3*,options=header]
|===
|Name
|Type
|Description

|connected
|boolean
a|True if the initiator is currently logged in to this connection's interface.


|interface
|link:#interface[interface]
a|

|last_seen_time
|string
a|The last time this initiator logged in. Logins not seen for 48 hours are cleared and not reported.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#connections]
[.api-collapsible-fifth-title]
connections

[cols=3*,options=header]
|===
|Name
|Type
|Description

|logins
|array[link:#logins[logins]]
a|

|node
|link:#node[node]
a|

|===


[#connectivity_tracking]
[.api-collapsible-fifth-title]
connectivity_tracking

Overview of the initiator's connections to ONTAP.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|alerts
|array[link:#alerts[alerts]]
a|

|connection_state
|string
a|Connection state.


|connections
|array[link:#connections[connections]]
a|

|===


[#igroup]
[.api-collapsible-fifth-title]
igroup

The initiator group in which the initiator is found.

Note that this does not mean that the initiator cannot also be found in other initiator groups.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the initiator group.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#records]
[.api-collapsible-fifth-title]
records

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|name
|string
a|The FC WWPN, iSCSI IQN, or iSCSI EUI that identifies the host initiator. Valid in POST only and not allowed when the `records` property is used.

An FC WWPN consists of 16 hexadecimal digits grouped as 8 pairs separated by colons. The format for an iSCSI IQN is _iqn.yyyy-mm.reverse_domain_name:any_. The iSCSI EUI format consists of the _eui._ prefix followed by 16 hexadecimal characters.


|===


[#igroup_initiator]
[.api-collapsible-fifth-title]
igroup_initiator

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|connectivity_tracking
|link:#connectivity_tracking[connectivity_tracking]
a|Overview of the initiator's connections to ONTAP.

* readOnly: 1
* Introduced in: 9.11


|igroup
|link:#igroup[igroup]
a|The initiator group in which the initiator is found.

Note that this does not mean that the initiator cannot also be found in other initiator groups.


|name
|string
a|The FC WWPN, iSCSI IQN, or iSCSI EUI that identifies the host initiator. Valid in POST only and not allowed when the `records` property is used.

An FC WWPN consists of 16 hexadecimal digits grouped as 8 pairs separated by colons. The format for an iSCSI IQN is _iqn.yyyy-mm.reverse_domain_name:any_. The iSCSI EUI format consists of the _eui._ prefix followed by 16 hexadecimal characters.


|records
|array[link:#records[records]]
a|An array of initiators specified to add multiple initiators to an initiator group in a single API call. Not allowed when the `name` property is used.


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
