---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-security-roles--privileges.html'
summary: 'Add a privilege tuple to an existing role'
---

= Add a privilege tuple to an existing role

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/security/roles/{owner.uuid}/{name}/privileges`#

*Introduced In:* 9.6

Adds a privilege tuple (of REST URI or command/command directory path, its access level and an optional query, if the "path" refers to a command/command directory path) to an existing role.

== Required parameters

* `owner.uuid` - UUID of the SVM that houses this role.
* `name` - Name of the role to be updated.
* `path` - REST URI path (example: _/api/storage/volumes_) or command/command directory path (example: _snaplock compliance-clock_). Can be a resource-qualified endpoint (example: _/api/storage/volumes/43256a71-be02-474d-a2a9-9642e12a6a2c/snapshots_). Currently, resource-qualified endpoints are limited to the "snapshots" endpoint: _/api/storage/volumes/{volume.uuid}/snapshots_ and _/api/storage/volumes/*/snapshots_. "*" is a wildcard character denoting "all" volumes.
* `access` - Desired access level for the REST URI path or command/command directory.

== Related ONTAP commands

* `security login rest-role create`
* `security login role create`

== Learn more

* link:manage_role_privilege_details.html[DOC /security/roles/{owner.uuid}/\{name}/privileges]
* link:manage_security_roles.html[DOC /security/roles]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|owner.uuid
|string
|path
|True
a|Role owner UUID


|name
|string
|path
|True
a|Role name


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|string
a|Access level for the REST endpoint or command/command directory path. If it denotes the access level for a command/command directory path, the only supported enum values are 'none','readonly' and 'all'.


|path
|string
a|Either of REST URI/endpoint OR command/command directory path.


|query
|string
a|Optional attribute that can be specified only if the "path" attribute refers to a command/command directory path. The privilege tuple implicitly defines a set of objects the role can or cannot access at the specified access level. The query further reduces this set of objects to a subset of objects that the role is allowed to access. The query attribute must be applicable to the command/command directory specified by the "path" attribute. It is defined using one or more parameters of the command/command directory path specified by the "path" attribute.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "access": "readonly",
  "path": [
    "/api/cluster/jobs",
    "/api/storage/volumes",
    "job schedule interval",
    "volume move"
  ],
  "query": [
    "-days <1 -hours >12",
    "-vserver vs1|vs2|vs3 -destination-aggregate aggr1|aggr2"
  ]
}
====

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 5636129
| A role with given name has not been defined.

| 5636143
| A Vserver admin cannot use the API with this access level.

| 5636144
| The value specified for the access level is not valid.

| 5636169
| A character in the URI is not valid.

| 5636170
| The URI does not exist.

| 5636173
| This feature requires an effective cluster version of 9.6 or later.

| 5636175
| Vserver admin cannot have access to given API.

| 5636184
| Expanded REST roles for granular resource control feature is currently disabled.

| 5636185
| The specified UUID was not found.

| 5636186
| Expanded REST roles for granular resource control requires an effective cluster version of 9.10.1 or later.

| 13434890
| Vserver-ID failed for Vserver roles.

| 13434891
| UUID LookUp failed for Vserver roles.

| 13434892
| Roles is a required field.

| 13434893
| The SVM does not exist.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#role_privilege]
[.api-collapsible-fifth-title]
role_privilege

A tuple containing a REST endpoint or a command/command directory path and the access level assigned to that endpoint or command/command directory. If the "path" attribute refers to a command/command directory path, the tuple could additionally contain an optional query. The REST endpoint can be a resource-qualified endpoint. At present, the only supported resource-qualified endpoints are _/api/storage/volumes/{volume.uuid}/snapshots_ and _/api/storage/volumes/*/snapshots_. "*" is a wildcard character denoting "all" volumes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|string
a|Access level for the REST endpoint or command/command directory path. If it denotes the access level for a command/command directory path, the only supported enum values are 'none','readonly' and 'all'.


|path
|string
a|Either of REST URI/endpoint OR command/command directory path.


|query
|string
a|Optional attribute that can be specified only if the "path" attribute refers to a command/command directory path. The privilege tuple implicitly defines a set of objects the role can or cannot access at the specified access level. The query further reduces this set of objects to a subset of objects that the role is allowed to access. The query attribute must be applicable to the command/command directory specified by the "path" attribute. It is defined using one or more parameters of the command/command directory path specified by the "path" attribute.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
