---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-application-consistency-groups.html'
summary: 'Create a consistency group'
---

= Create a consistency group

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/application/consistency-groups`#

*Introduced In:* 9.10

Creates a consistency group with one or more consistency groups having:

* new SAN volumes,
* existing SAN, NVMe or NAS FlexVol volumes in a new or existing consistency group

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the group.
* `volumes`, `luns` or `namespaces`

== Naming Conventions

== Consistency groups

*** name or consistency_groups[].name, if specified

*** derived from volumes[0].name, if only one volume is specified, same as volume name

== Volume

*** volumes[].name, if specified

*** derived from volume prefix in luns[].name

*** derived from cg[].name, suffixed by "_#" where "#" is a system generated unique number

*** suffixed by "_#" where "#" is a system generated unique number, if provisioning_options.count is provided

== LUN

*** luns[].name, if specified

*** derived from volumes[].name, suffixed by "_#" where "#" is a system generated unique number

*** suffixed by "_#" where "#" is a system generated unique number, if provisioning_options.count is provided

== NVMe Namespace

*** namespaces[].name, if specified

*** derived from volumes[].name, suffixed by "_#" where "#" is a system generated unique number

*** suffixed by "_#" where "#" is a system generated unique number, if provisioning_options.count is provided

== Related ONTAP commands

There are no ONTAP commands for managing consistency group.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|consistency_groups
|array[link:#consistency_groups[consistency_groups]]
a|A consistency group is a mutually exclusive aggregation of volumes or other consistency groups. A consistency group can only be associated with one direct parent consistency group.


|luns
|array[link:#luns[luns]]
a|The LUNs array can be used to create or modify LUNs in a consistency group on a new or existing volume that is a member of the consistency group. LUNs are considered members of a consistency group if they are located on a volume that is a member of the consistency group.


|name
|string
a|Name of the consistency group. The consistency group name must be unique within an SVM.

If not provided and the consistency group contains only one volume, the name will be generated based on the volume name. If the consistency group contains more than one volume, the name is required.


|namespaces
|array[link:#namespaces[namespaces]]
a|An NVMe namespace is a collection of addressable logical blocks presented to hosts connected to the SVM using the NVMe over Fabrics protocol.
In ONTAP, an NVMe namespace is located within a volume. Optionally, it can be located within a qtree in a volume.

An NVMe namespace is created to a specified size using thin or thick provisioning as determined by the volume on which it is created. NVMe namespaces support being cloned. An NVMe namespace cannot be renamed, resized, or moved to a different volume. NVMe namespaces do not support the assignment of a QoS policy for performance management, but a QoS policy can be assigned to the volume containing the namespace. See the NVMe namespace object model to learn more about each of the properties supported by the NVMe namespace REST API.

An NVMe namespace must be mapped to an NVMe subsystem to grant access to the subsystem's hosts. Hosts can then access the NVMe namespace and perform I/O using the NVMe over Fabrics protocol.

* maxItems: 16
* minItems: 0
* uniqueItems: 1
* Introduced in: 9.10
* x-ntap-modifyOnly: true


|provisioning_options
|link:#provisioning_options[provisioning_options]
a|Options that are applied to the operation.


|qos
|link:#qos[qos]
a|

|restore_to
|link:#restore_to[restore_to]
a|Use to restore a consistency group to a previous Snapshot copy


|snapshot_policy
|link:#snapshot_policy_reference[snapshot_policy_reference]
a|This is a reference to the Snapshot copy policy.


|svm
|link:#svm[svm]
a|The Storage Virtual Machine (SVM) in which the consistency group is located.


|tiering
|link:#tiering[tiering]
a|The tiering placement and policy definitions for volumes in this consistency group.


|volumes
|array[link:#volumes[volumes]]
a|A consistency group is a mutually exclusive aggregation of volumes or other consistency groups. A volume can only be associated with one direct parent consistency group.

The volumes array can be used to create new volumes in the consistency group, add existing volumes to the consistency group, or modify existing volumes that are already members of the consistency group.

The total number of volumes across all child consistency groups contained in a consistency group is constrained by the same limit.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "consistency_groups": [
    {
      "luns": [
        {
          "clone": {
            "source": {
              "name": "/vol/volume1/lun1",
              "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
            }
          },
          "comment": "string",
          "create_time": "2018-06-04T19:00:00Z",
          "enabled": null,
          "lun_maps": [
            {
              "igroup": {
                "comment": "string",
                "igroups": [
                  {
                    "name": "igroup1",
                    "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
                  }
                ],
                "initiators": [
                  {
                    "comment": "my comment",
                    "name": "iqn.1998-01.com.corp.iscsi:name1"
                  }
                ],
                "name": "igroup1",
                "os_type": "string",
                "protocol": "string",
                "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
              }
            }
          ],
          "name": "/vol/volume1/lun1",
          "os_type": "string",
          "provisioning_options": {
            "action": "string"
          },
          "serial_number": "string",
          "space": {
            "guarantee": {
              "reserved": null
            },
            "size": 1073741824
          },
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      ],
      "name": "string",
      "namespaces": [
        {
          "comment": "string",
          "create_time": "2018-06-04T19:00:00Z",
          "name": "/vol/volume1/qtree1/namespace1",
          "os_type": "string",
          "provisioning_options": {
            "action": "string"
          },
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      ],
      "provisioning_options": {
        "action": "string",
        "storage_service": {
          "name": "string"
        }
      },
      "qos": {
        "policy": {
          "max_throughput_iops": 10000,
          "max_throughput_mbps": 500,
          "min_throughput_iops": 2000,
          "min_throughput_mbps": 500,
          "name": "performance",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      },
      "restore_to": {
        "snapshot": {
          "name": "string",
          "uuid": "string"
        }
      },
      "snapshot_policy": {
        "name": "default",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "tiering": {
        "control": "string",
        "policy": "string"
      },
      "volumes": [
        {
          "comment": "string",
          "language": "string",
          "name": "vol_cs_dept",
          "provisioning_options": {
            "action": "string",
            "storage_service": {
              "name": "string"
            }
          },
          "qos": {
            "policy": {
              "max_throughput_iops": 10000,
              "max_throughput_mbps": 500,
              "min_throughput_iops": 2000,
              "min_throughput_mbps": 500,
              "name": "performance",
              "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
            }
          },
          "snapshot_policy": {
            "name": "default",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "tiering": {
            "control": "string",
            "policy": "string"
          },
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      ]
    }
  ],
  "luns": [
    {
      "clone": {
        "source": {
          "name": "/vol/volume1/lun1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      },
      "comment": "string",
      "create_time": "2018-06-04T19:00:00Z",
      "enabled": null,
      "lun_maps": [
        {
          "igroup": {
            "comment": "string",
            "igroups": [
              {
                "name": "igroup1",
                "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
              }
            ],
            "initiators": [
              {
                "comment": "my comment",
                "name": "iqn.1998-01.com.corp.iscsi:name1"
              }
            ],
            "name": "igroup1",
            "os_type": "string",
            "protocol": "string",
            "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
          }
        }
      ],
      "name": "/vol/volume1/lun1",
      "os_type": "string",
      "provisioning_options": {
        "action": "string"
      },
      "serial_number": "string",
      "space": {
        "guarantee": {
          "reserved": null
        },
        "size": 1073741824
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "name": "string",
  "namespaces": [
    {
      "comment": "string",
      "create_time": "2018-06-04T19:00:00Z",
      "name": "/vol/volume1/qtree1/namespace1",
      "os_type": "string",
      "provisioning_options": {
        "action": "string"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "provisioning_options": {
    "action": "string",
    "storage_service": {
      "name": "string"
    }
  },
  "qos": {
    "policy": {
      "max_throughput_iops": 10000,
      "max_throughput_mbps": 500,
      "min_throughput_iops": 2000,
      "min_throughput_mbps": 500,
      "name": "performance",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  },
  "replicated": null,
  "replication_source": null,
  "restore_to": {
    "snapshot": {
      "name": "string",
      "uuid": "string"
    }
  },
  "snapshot_policy": {
    "name": "default",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "tiering": {
    "control": "string",
    "policy": "string"
  },
  "volumes": [
    {
      "comment": "string",
      "language": "string",
      "name": "vol_cs_dept",
      "provisioning_options": {
        "action": "string",
        "storage_service": {
          "name": "string"
        }
      },
      "qos": {
        "policy": {
          "max_throughput_iops": 10000,
          "max_throughput_mbps": 500,
          "min_throughput_iops": 2000,
          "min_throughput_mbps": 500,
          "name": "performance",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        }
      },
      "snapshot_policy": {
        "name": "default",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "tiering": {
        "control": "string",
        "policy": "string"
      },
      "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
    }
  ]
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 53411842
| Consistency group does not exist.

| 53411843
| A consistency group with specified UUID was not found.

| 53411844
| Specified consistency group was not found in the specified SVM.

| 53411845
| The specified UUID and name refer to different consistency groups.

| 53411846
| Either name or UUID must be provided.

| 53411853
| Fields provided in the request conflict with each other.

| 53411856
| Field provided is only supported when provisioning new objects.

| 53411857
| LUNs that are not members of the application are not supported by this API. LUNs can be added to an application by adding the volume containing the LUNs to the application.

| 53411860
| An object with the same identifier in the same scope exists.

| 53411861
| Volume specified does not exist in provided volume array.

| 53411862
| Modifying existing igroups is not supported using this API.

| 53411864
| Request content insufficient to add an existing volume to an application.

| 53411865
| Volumes contained in one consistency group can not be added to a different consistency group.

| 53411866
| LUNs are not supported on FlexGroups volumes.

| 53411867
| LUN name is too long after appending a unique suffix.

| 53411869
| Volume name is too long after appending a unique suffix.

| 53411870
| When using the "round_robin" layout, the volume count must not be greater than the LUN count.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#self_link]
[.api-collapsible-fifth-title]
self_link
[#source]
[.api-collapsible-fifth-title]
source

The source LUN for a LUN clone operation. This can be specified using property `clone.source.uuid` or `clone.source.name`. If both properties are supplied, they must refer to the same LUN.

Valid in POST to create a new LUN as a clone of the source.

Valid in PATCH to overwrite an existing LUN's data as a clone of another.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The fully qualified path name of the clone source LUN composed of a "/vol" prefix, the volume name, the (optional) qtree name, and base name of the LUN. Valid in POST and PATCH.


|uuid
|string
a|The unique identifier of the clone source LUN. Valid in POST and PATCH.


|===


[#clone]
[.api-collapsible-fifth-title]
clone

This sub-object is used in POST to create a new LUN as a clone of an existing LUN, or PATCH to overwrite an existing LUN as a clone of another. Setting a property in this sub-object indicates that a LUN clone is desired. Consider the following other properties when cloning a LUN: `auto_delete`, `qos_policy`, `space.guarantee.requested` and `space.scsi_thin_provisioning_support_enabled`.

When used in a PATCH, the patched LUN's data is over-written as a clone of the source and the following properties are preserved from the patched LUN unless otherwise specified as part of the PATCH: `class`, `auto_delete`, `lun_maps`, `serial_number`, `status.state`, and `uuid`.

Persistent reservations for the patched LUN are also preserved.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|source
|link:#source[source]
a|The source LUN for a LUN clone operation. This can be specified using property `clone.source.uuid` or `clone.source.name`. If both properties are supplied, they must refer to the same LUN.

Valid in POST to create a new LUN as a clone of the source.

Valid in PATCH to overwrite an existing LUN's data as a clone of another.


|===


[#igroups]
[.api-collapsible-fifth-title]
igroups

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the initiator group.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#initiators]
[.api-collapsible-fifth-title]
initiators

The initiators that are members of the initiator group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator.


|name
|string
a|Name of initiator that is a member of the initiator group.


|===


[#igroup]
[.api-collapsible-fifth-title]
igroup

The initiator group that directly owns the initiator, which is where modification of the initiator is supported. This property will only be populated when the initiator is a member of a nested initiator group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment available for use by the administrator. Valid in POST and PATCH.


|igroups
|array[link:#igroups[igroups]]
a|Separate igroup definitions to include in this igroup.


|initiators
|array[link:#initiators[initiators]]
a|The initiators that are members of the group.


|name
|string
a|The name of the initiator group. Required in POST; optional in PATCH.


|os_type
|string
a|The host operating system of the initiator group. All initiators in the group should be hosts of the same operating system. Required in POST; optional in PATCH.


|protocol
|string
a|The protocols supported by the initiator group. This restricts the type of initiators that can be added to the initiator group. Optional in POST; if not supplied, this defaults to _mixed_.

The protocol of an initiator group cannot be changed after creation of the group.


|uuid
|string
a|The unique identifier of the initiator group.


|===


[#lun_maps]
[.api-collapsible-fifth-title]
lun_maps

A LUN map is an association between a LUN and an initiator group.

When a LUN is mapped to an initiator group, the initiator group's initiators are granted access to the LUN. The relationship between a LUN and an initiator group is many LUNs to many initiator groups.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|igroup
|link:#igroup[igroup]
a|The initiator group that directly owns the initiator, which is where modification of the initiator is supported. This property will only be populated when the initiator is a member of a nested initiator group.


|logical_unit_number
|integer
a|The logical unit number assigned to the LUN when mapped to the specified initiator group. The number is used to identify the LUN to initiators in the initiator group when communicating through the Fibre Channel Protocol or iSCSI. Optional in POST; if no value is provided, ONTAP assigns the lowest available value.

* Introduced in: 9.6
* readCreate: 1


|===


[#provisioning_options]
[.api-collapsible-fifth-title]
provisioning_options

Options that are applied to the operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|action
|string
a|Operation to perform


|count
|integer
a|Number of elements to perform the operation on.


|===


[#policy]
[.api-collapsible-fifth-title]
policy

The QoS policy

[#qos]
[.api-collapsible-fifth-title]
qos

[cols=3*,options=header]
|===
|Name
|Type
|Description

|policy
|link:#policy[policy]
a|The QoS policy


|===


[#guarantee]
[.api-collapsible-fifth-title]
guarantee

Properties that request and report the space guarantee for the LUN.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|requested
|boolean
a|The requested space reservation policy for the LUN. If _true_, a space reservation is requested for the LUN; if _false_, the LUN is thin provisioned. Guaranteeing a space reservation request for a LUN requires that the volume in which the LUN resides is also space reserved and that the fractional reserve for the volume is 100%. Valid in POST and PATCH.


|===


[#space]
[.api-collapsible-fifth-title]
space

The storage space related properties of the LUN.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|guarantee
|link:#guarantee[guarantee]
a|Properties that request and report the space guarantee for the LUN.


|size
|integer
a|The total provisioned size of the LUN. The LUN size can be increased but not reduced using the REST interface.
The maximum and minimum sizes listed here are the absolute maximum and absolute minimum sizes, in bytes. The actual minimum and maxiumum sizes vary depending on the ONTAP version, ONTAP platform, and the available space in the containing volume and aggregate.
For more information, see _Size properties_ in the _docs_ section of the ONTAP REST API documentation.

* example: 1073741824
* format: int64
* Max value: 140737488355328
* Min value: 4096
* Introduced in: 9.6


|===


[#luns]
[.api-collapsible-fifth-title]
luns

A LUN is the logical representation of storage in a storage area network (SAN).

In ONTAP, a LUN is located within a volume. Optionally, it can be located within a qtree in a volume.

A LUN can be created to a specified size using thin or thick provisioning. A LUN can then be renamed, resized, cloned, and moved to a different volume. LUNs support the assignment of a quality of service (QoS) policy for performance management or a QoS policy can be assigned to the volume containing the LUN. See the LUN object model to learn more about each of the properties supported by the LUN REST API.

A LUN must be mapped to an initiator group to grant access to the initiator group's initiators (client hosts). Initiators can then access the LUN and perform I/O over a Fibre Channel (FC) fabric using the Fibre Channel Protocol or a TCP/IP network using iSCSI.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|clone
|link:#clone[clone]
a|This sub-object is used in POST to create a new LUN as a clone of an existing LUN, or PATCH to overwrite an existing LUN as a clone of another. Setting a property in this sub-object indicates that a LUN clone is desired. Consider the following other properties when cloning a LUN: `auto_delete`, `qos_policy`, `space.guarantee.requested` and `space.scsi_thin_provisioning_support_enabled`.

When used in a PATCH, the patched LUN's data is over-written as a clone of the source and the following properties are preserved from the patched LUN unless otherwise specified as part of the PATCH: `class`, `auto_delete`, `lun_maps`, `serial_number`, `status.state`, and `uuid`.

Persistent reservations for the patched LUN are also preserved.


|comment
|string
a|A configurable comment available for use by the administrator. Valid in POST and PATCH.


|create_time
|string
a|The time the LUN was created.


|lun_maps
|array[link:#lun_maps[lun_maps]]
a|An array of LUN maps.

A LUN map is an association between a LUN and an initiator group. When a LUN is mapped to an initiator group, the initiator group's initiators are granted access to the LUN. The relationship between a LUN and an initiator group is many LUNs to many initiator groups.


|name
|string
a|The fully qualified path name of the LUN composed of the "/vol" prefix, the volume name, the qtree name (optional), and the base name of the LUN. Valid in POST and PATCH.


|os_type
|string
a|The operating system type of the LUN.

Required in POST when creating a LUN that is not a clone of another. Disallowed in POST when creating a LUN clone.


|provisioning_options
|link:#provisioning_options[provisioning_options]
a|Options that are applied to the operation.


|qos
|link:#qos[qos]
a|

|serial_number
|string
a|The LUN serial number. The serial number is generated by ONTAP when the LUN is created.

* maxLength: 12
* minLength: 12
* readOnly: 1
* Introduced in: 9.10


|space
|link:#space[space]
a|The storage space related properties of the LUN.


|uuid
|string
a|The unique identifier of the LUN.  The UUID is generated by ONTAP when the LUN is created.

* example: 1cd8a442-86d1-11e0-ae1c-123478563412
* readOnly: 1
* Introduced in: 9.10


|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#nvme_subsystem_reference]
[.api-collapsible-fifth-title]
nvme_subsystem_reference

An NVMe subsystem maintains configuration state and NVMe namespace access control for a set of NVMe-connected hosts.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the NVMe subsystem.


|uuid
|string
a|The unique identifier of the NVMe subsystem.


|===


[#subsystem_map]
[.api-collapsible-fifth-title]
subsystem_map

The NVMe subsystem with which the NVMe namespace is associated. A namespace can be mapped to zero (0) or one (1) subsystems.

There is an added cost to retrieving property values for `subsystem_map`.
They are not populated for either a collection GET or an instance GET unless explicitly requested using the `fields` query parameter.

[#namespaces]
[.api-collapsible-fifth-title]
namespaces

An NVMe namespace is a collection of addressable logical blocks presented to hosts connected to the storage virtual machine using the NVMe over Fabrics protocol.

In ONTAP, an NVMe namespace is located within a volume. Optionally, it can be located within a qtree in a volume.

An NVMe namespace is created to a specified size using thin or thick provisioning as determined by the volume on which it is created. NVMe namespaces support being cloned. An NVMe namespace cannot be renamed, resized, or moved to a different volume. NVMe namespaces do not support the assignment of a QoS policy for performance management, but a QoS policy can be assigned to the volume containing the namespace. See the NVMe namespace object model to learn more about each of the properties supported by the NVMe namespace REST API.

An NVMe namespace must be mapped to an NVMe subsystem to grant access to the subsystem's hosts. Hosts can then access the NVMe namespace and perform I/O using the NVMe over Fabrics protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|auto_delete
|boolean
a|This property marks the NVMe namespace for auto deletion when the volume containing the namespace runs out of space. This is most commonly set on namespace clones.

When set to _true_, the NVMe namespace becomes eligible for automatic deletion when the volume runs out of space. Auto deletion only occurs when the volume containing the namespace is also configured for auto deletion and free space in the volume decreases below a particular threshold.

This property is optional in POST and PATCH. The default value for a new NVMe namespace is _false_.

There is an added cost to retrieving this property's value. It is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|comment
|string
a|A configurable comment available for use by the administrator. Valid in POST and PATCH.


|create_time
|string
a|The time the NVMe namespace was created.


|enabled
|boolean
a|The enabled state of the NVMe namespace. Certain error conditions cause the namespace to become disabled. If the namespace is disabled, you can check the `state` property to determine what error disabled the namespace. An NVMe namespace is enabled automatically when it is created.


|name
|string
a|The fully qualified path name of the NVMe namespace composed of a "/vol" prefix, the volume name, the (optional) qtree name and base name of the namespace. Valid in POST.

NVMe namespaces do not support rename, or movement between volumes.


|os_type
|string
a|The operating system type of the NVMe namespace.

Required in POST when creating an NVMe namespace that is not a clone of another. Disallowed in POST when creating a namespace clone.


|provisioning_options
|link:#provisioning_options[provisioning_options]
a|Options that are applied to the operation.


|subsystem_map
|array[link:#subsystem_map[subsystem_map]]
a|The NVMe subsystem with which the NVMe namespace is associated. A namespace can be mapped to zero (0) or one (1) subsystems.

There is an added cost to retrieving property values for `subsystem_map`. They are not populated for either a collection GET or an instance GET unless explicitly requested using the `fields` query parameter.


|uuid
|string
a|The unique identifier of the NVMe namespace.


|===


[#parent_consistency_group]
[.api-collapsible-fifth-title]
parent_consistency_group

The parent consistency group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the consistency group.


|uuid
|string
a|The unique identifier of the consistency group.


|===


[#storage_service]
[.api-collapsible-fifth-title]
storage_service

Determines the placement of any storage object created during this operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Storage service name. If not specified, the default value is the most performant for the platform.


|===


[#provisioning_options]
[.api-collapsible-fifth-title]
provisioning_options

Options that are applied to the operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|action
|string
a|Operation to perform


|storage_service
|link:#storage_service[storage_service]
a|Determines the placement of any storage object created during this operation.


|===


[#policy]
[.api-collapsible-fifth-title]
policy

The QoS policy


[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|max_throughput_mbps
|integer
a|Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none. Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH.


|min_throughput_mbps
|integer
a|Specifies the minimum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#snapshot]
[.api-collapsible-fifth-title]
snapshot

A consistency group's Snapshot copy


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the consistency group's Snapshot copy to restore to.


|uuid
|string
a|The UUID of the consistency group's Snapshot copy to restore to.


|===


[#restore_to]
[.api-collapsible-fifth-title]
restore_to

Use to restore a consistency group to a previous Snapshot copy


[cols=3*,options=header]
|===
|Name
|Type
|Description

|snapshot
|link:#snapshot[snapshot]
a|A consistency group's Snapshot copy


|===


[#snapshot_policy_reference]
[.api-collapsible-fifth-title]
snapshot_policy_reference

This is a reference to the Snapshot copy policy.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#space]
[.api-collapsible-fifth-title]
space

Space information for the consistency group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|available
|integer
a|The amount of space available in the consistency group, in bytes.


|size
|integer
a|The total provisioned size of the consistency group, in bytes.


|used
|integer
a|The amount of space consumed in the consistency group, in bytes.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

The Storage Virtual Machine (SVM) in which the consistency group is located.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#tiering]
[.api-collapsible-fifth-title]
tiering

The tiering placement and policy definitions for volumes in this consistency group.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|control
|string
a|Storage tiering placement rules for the object.


|policy
|string
a|Policy that determines whether the user data blocks of a volume in a FabricPool will be tiered to the cloud store when they become cold.

FabricPool combines flash (performance tier) with a cloud store into a single aggregate. Temperature of a volume block increases if it is accessed frequently and decreases when it is not. Valid in POST or PATCH.

all &dash; Allows tiering of both Snapshot copies and active file system user data to the cloud store as soon as possible by ignoring the temperature on the volume blocks.

auto &dash; Allows tiering of both snapshot and active file system user data to the cloud store

none &dash; Volume blocks are not be tiered to the cloud store.

snapshot_only &dash; Allows tiering of only the volume Snapshot copies not associated with the active file system.

The default tiering policy is "snapshot-only" for a FlexVol volume and "none" for a FlexGroup volume. The default minimum cooling period for the "snapshot-only" tiering policy is 2 days and for the "auto" tiering policy it is 31 days.


|===


[#provisioning_options]
[.api-collapsible-fifth-title]
provisioning_options

Options that are applied to the operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|action
|string
a|Operation to perform


|count
|integer
a|Number of elements to perform the operation on.


|storage_service
|link:#storage_service[storage_service]
a|Determines the placement of any storage object created during this operation.


|===


[#qos]
[.api-collapsible-fifth-title]
qos

The QoS policy for this volume.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|policy
|link:#policy[policy]
a|The QoS policy


|===


[#space]
[.api-collapsible-fifth-title]
space

[cols=3*,options=header]
|===
|Name
|Type
|Description

|size
|integer
a|Total provisioned size, in bytes.


|===


[#tiering]
[.api-collapsible-fifth-title]
tiering

The tiering placement and policy definitions for this volume.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|control
|string
a|Storage tiering placement rules for the object.


|policy
|string
a|Policy that determines whether the user data blocks of a volume in a FabricPool will be tiered to the cloud store when they become cold.

FabricPool combines flash (performance tier) with a cloud store into a single aggregate. Temperature of a volume block increases if it is accessed frequently and decreases when it is not. Valid in POST or PATCH.

all &dash; Allows tiering of both Snapshot copies and active file system user data to the cloud store as soon as possible by ignoring the temperature on the volume blocks.

auto &dash; Allows tiering of both snapshot and active file system user data to the cloud store

none &dash; Volume blocks are not be tiered to the cloud store.

snapshot_only &dash; Allows tiering of only the volume Snapshot copies not associated with the active file system.

The default tiering policy is "snapshot-only" for a FlexVol volume and "none" for a FlexGroup volume. The default minimum cooling period for the "snapshot-only" tiering policy is 2 days and for the "auto" tiering policy it is 31 days.


|===


[#volumes]
[.api-collapsible-fifth-title]
volumes

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A comment for the volume. Valid in POST or PATCH.


|language
|string
a|Language encoding setting for volume. If no language is specified, the volume inherits its SVM language encoding setting.


|name
|string
a|Volume name. The name of volume must start with an alphabetic character (a to z or A to Z) or an underscore (_). The name must be 197 or fewer characters in length for FlexGroups, and 203 or fewer characters in length for all other types of volumes. Volume names must be unique within an SVM. Required on POST.


|provisioning_options
|link:#provisioning_options[provisioning_options]
a|Options that are applied to the operation.


|qos
|link:#qos[qos]
a|The QoS policy for this volume.


|snapshot_policy
|link:#snapshot_policy_reference[snapshot_policy_reference]
a|This is a reference to the Snapshot copy policy.


|space
|link:#space[space]
a|

|tiering
|link:#tiering[tiering]
a|The tiering placement and policy definitions for this volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* readOnly: 1
* Introduced in: 9.8


|===


[#consistency_groups]
[.api-collapsible-fifth-title]
consistency_groups

[cols=3*,options=header]
|===
|Name
|Type
|Description

|luns
|array[link:#luns[luns]]
a|The LUNs array can be used to create or modify LUNs in a consistency group on a new or existing volume that is a member of the consistency group. LUNs are considered members of a consistency group if they are located on a volume that is a member of the consistency group.


|name
|string
a|Name of the consistency group. The consistency group name must be unique within an SVM.

If not provided and the consistency group contains only one volume, the name will be generated based on the volume name. If the consistency group contains more than one volume, the name is required.


|namespaces
|array[link:#namespaces[namespaces]]
a|An NVMe namespace is a collection of addressable logical blocks presented to hosts connected to the SVM using the NVMe over Fabrics protocol.
In ONTAP, an NVMe namespace is located within a volume. Optionally, it can be located within a qtree in a volume.

An NVMe namespace is created to a specified size using thin or thick provisioning as determined by the volume on which it is created. NVMe namespaces support being cloned. An NVMe namespace cannot be renamed, resized, or moved to a different volume. NVMe namespaces do not support the assignment of a QoS policy for performance management, but a QoS policy can be assigned to the volume containing the namespace. See the NVMe namespace object model to learn more about each of the properties supported by the NVMe namespace REST API.

An NVMe namespace must be mapped to an NVMe subsystem to grant access to the subsystem's hosts. Hosts can then access the NVMe namespace and perform I/O using the NVMe over Fabrics protocol.

* maxItems: 16
* minItems: 0
* uniqueItems: 1
* Introduced in: 9.10
* x-ntap-modifyOnly: true


|provisioning_options
|link:#provisioning_options[provisioning_options]
a|Options that are applied to the operation.


|qos
|link:#qos[qos]
a|

|restore_to
|link:#restore_to[restore_to]
a|Use to restore a consistency group to a previous Snapshot copy


|snapshot_policy
|link:#snapshot_policy_reference[snapshot_policy_reference]
a|This is a reference to the Snapshot copy policy.


|svm
|link:#svm[svm]
a|The Storage Virtual Machine (SVM) in which the consistency group is located.


|tiering
|link:#tiering[tiering]
a|The tiering placement and policy definitions for volumes in this consistency group.


|volumes
|array[link:#volumes[volumes]]
a|A consistency group is a mutually exclusive aggregation of volumes or other consistency groups. A volume can only be associated with one direct parent consistency group.

The volumes array can be used to create new volumes in the consistency group, add existing volumes to the consistency group, or modify existing volumes that are already members of the consistency group.

The total number of volumes across all child consistency groups contained in a consistency group is constrained by the same limit.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

The Storage Virtual Machine (SVM) in which the consistency group is located.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#consistency_group]
[.api-collapsible-fifth-title]
consistency_group

[cols=3*,options=header]
|===
|Name
|Type
|Description

|consistency_groups
|array[link:#consistency_groups[consistency_groups]]
a|A consistency group is a mutually exclusive aggregation of volumes or other consistency groups. A consistency group can only be associated with one direct parent consistency group.


|luns
|array[link:#luns[luns]]
a|The LUNs array can be used to create or modify LUNs in a consistency group on a new or existing volume that is a member of the consistency group. LUNs are considered members of a consistency group if they are located on a volume that is a member of the consistency group.


|name
|string
a|Name of the consistency group. The consistency group name must be unique within an SVM.

If not provided and the consistency group contains only one volume, the name will be generated based on the volume name. If the consistency group contains more than one volume, the name is required.


|namespaces
|array[link:#namespaces[namespaces]]
a|An NVMe namespace is a collection of addressable logical blocks presented to hosts connected to the SVM using the NVMe over Fabrics protocol.
In ONTAP, an NVMe namespace is located within a volume. Optionally, it can be located within a qtree in a volume.

An NVMe namespace is created to a specified size using thin or thick provisioning as determined by the volume on which it is created. NVMe namespaces support being cloned. An NVMe namespace cannot be renamed, resized, or moved to a different volume. NVMe namespaces do not support the assignment of a QoS policy for performance management, but a QoS policy can be assigned to the volume containing the namespace. See the NVMe namespace object model to learn more about each of the properties supported by the NVMe namespace REST API.

An NVMe namespace must be mapped to an NVMe subsystem to grant access to the subsystem's hosts. Hosts can then access the NVMe namespace and perform I/O using the NVMe over Fabrics protocol.

* maxItems: 16
* minItems: 0
* uniqueItems: 1
* Introduced in: 9.10
* x-ntap-modifyOnly: true


|provisioning_options
|link:#provisioning_options[provisioning_options]
a|Options that are applied to the operation.


|qos
|link:#qos[qos]
a|

|restore_to
|link:#restore_to[restore_to]
a|Use to restore a consistency group to a previous Snapshot copy


|snapshot_policy
|link:#snapshot_policy_reference[snapshot_policy_reference]
a|This is a reference to the Snapshot copy policy.


|svm
|link:#svm[svm]
a|The Storage Virtual Machine (SVM) in which the consistency group is located.


|tiering
|link:#tiering[tiering]
a|The tiering placement and policy definitions for volumes in this consistency group.


|volumes
|array[link:#volumes[volumes]]
a|A consistency group is a mutually exclusive aggregation of volumes or other consistency groups. A volume can only be associated with one direct parent consistency group.

The volumes array can be used to create new volumes in the consistency group, add existing volumes to the consistency group, or modify existing volumes that are already members of the consistency group.

The total number of volumes across all child consistency groups contained in a consistency group is constrained by the same limit.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
