---
sidebar: sidebar
api: true
explorer: false
permalink: 'view_ssh_svms.html'
summary: 'View SSH SVMs'
---

= View SSH SVMs



=== Overview

This endpoint is used to retrieve the SSH security configuration for all SVMs. The configuration consists of SSH security parameters. The security algorithms include SSH key exchange algorithms, ciphers for payload encryption, MAC algorithms, and the maximum authentication retry attempts allowed before closing the connection. The SSH configuration for a newly created SVM is the same as the SSH configuration at cluster level. When the cluster SSH configuration is updated using _/security/ssh_ endpoint, the SSH configuration of existing SVMs is not impacted. To customize the SSH security parameters for a particular SVM, perform a PATCH operation on the _api/security/ssh/svms/{svm.uuid}_ endpoint.

== Example

=== Retrieving the SSH security configuration of all SVMs.

----

# The API:
GET "/api/security/ssh/svms"

# The call:
curl -X GET "https://<mgmt-ip>/api/security/ssh/svms"

# The response:
{
"num_records": 1,
"records": [
  {
    "svm": {
      "name": "svm1",
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7",
      "_links": {
        "self": {
          "href": "/api/svm/svms/02c9e252-41be-11e9-81d5-00a0986138f7"
        }
      }
    },
    "ciphers": [
      "aes256_ctr",
      "aes192_ctr",
      "aes128_ctr"
    ],
    "key_exchange_algorithms": [
      "diffie_hellman_group_exchange_sha256",
      "diffie_hellman_group14_sha1"
    ],
    "mac_algorithms": [
      "hmac_sha1",
      "hmac_sha2_512_etm"
    ],
    "max_authentication_retry_count": 6,
    "_links": {
      "self": {
        "href": "/api/security/ssh/svms/02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  }
],
"_links": {
  "next": {
    "href": "/api/resourcelink"
  },
  "self": {
    "href": "/api/resourcelink"
  }
}
}
----


